name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: textblueprints/sentiment-app
        tag_with_ref: true
        add_git_labels: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: update deployment
      uses: actions/docker-build-push-gcr-update-gke-deployment-action@v1.4
      with:
        service_account: ${{ secrets.GCLOUD_AUTH}}
        zone: 'us-central1-a'
        project_id: 'sentiment-rest-api-282720'
        registry: 'registry.hub.docker.com'
        image_name: 'textblueprints/sentiment-app:${{ github.event.release.tag_name }}'
        cluster: 'sentiment-app-cluster'
        namespace: 'default'
        deployment: 'sentiment-app'
        container: 'sentiment-app'
