name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: textblueprints/sentiment-app
        tag_with_ref: true
        add_git_labels: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: Get kubeconfig file from GKE
      uses: machine-learning-apps/gke-kubeconfig@master
      with:
        application_credentials: ${{ secrets.GCLOUD_AUTH }}
        project_id: ${{ secrets.PROJECT_ID }}
        location_zone: ${{ secrets.LOCATION_ZONE }}
        cluster_name: ${{ secrets.CLUSTER_NAME }}

    - name: deploy to cluster
      uses: sidhusmart/kubectl@v1.3
      env:
        KUBE_CONFIG_DATA: '/github/workspace/.kube/config'
        UNCODED: 'false'
      with:
        args: set image --record deployment.apps/sentiment-app container=textblueprints/sentiment-app:${{ github.event.release.tag_name }}
    - name: verify deployment
      uses: sidhusmart/kubectl@v1.3
      env:
        KUBE_CONFIG_DATA: '/github/workspace/.kube/config'
        KUBECTL_VERSION: "1.14"
      with:
        args: '"rollout status deployment.apps/sentiment-app"'
